tproxy-port: 7893
bind-address: "*"
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  use-host: true
  nameserver:
    - 1.1.1.1
  fallback:
    - 1.0.0.1
    - https://cloudflare-dns.com/dns-query
proxies:
  - name: sgdo
    server: idcx6.natanvpn.store
    port: 443
    type: vmess
    uuid: d8e510da-f907-47f8-a4be-f16d44c23c7e
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: idcx6.natanvpn.store
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: idcx6.natanvpn.store
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - sgdo
      - BEST-PING
      - DIRECT
  - name: BEST-PING
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 50
    proxies:
      - sgdo
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
