port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: digi13
    server: app.gopay.co.id
    port: 443
    type: vmess
    uuid: 8dc999af-0f59-4f4f-aec7-9c32df4d6805
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sg7.natanvpn.xyz
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: sg7.natanvpn.xyz
    udp: true
  - name: enet46
    server: app.gopay.co.id
    port: 443
    type: vmess
    uuid: 46bdb925-1dca-4a54-aa37-b0de26223b8c
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2.natanvpn.xyz
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: id2.natanvpn.xyz
    udp: true
  - name: vvip-sakai01
    server: app.gopay.co.id
    port: 443
    type: vmess
    uuid: 86ad8e87-b0a2-43d5-ac71-f389a5eca4c3
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: cdn-sg3ray.jagoan.vip
    network: ws
    ws-opts:
      path: /vvip
      headers:
        Host: cdn-sg3ray.jagoan.vip
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - digi13
      - enet46
      - vvip-sakai01
      - LOAD-BALANCE
      - DIRECT
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://hi.bonds.id/ping
    interval: 300
    proxies:
      - digi13
      - enet46
      - vvip-sakai01
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
